##配置数据库四要素 键不可改变
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
##   指定一个数据源
#    type: com.alibaba.druid.pool.DruidDataSource